### PR TITLE
Preserve interfaces of AsyncHandlers

### PR DESCRIPTION
**Pull request by markus-s24**
Use dynamic proxies to wrap AsyncHandlers so that all their interfaces
are preserved.

### CODE REVIEW

**Comment by slandelle** [comment]
@markus-s24 Looking great, thanks! Still, project no longer compiles as `RateLimitedThrottleRequestFilter` in `guava` module also uses the code you removed. Could you please make `wrap` a public static factory?

**Comment by slandelle** [comment]
@markus-s24 Have you run the test suite locally? CI has been stalled for 40 minutes while it usually takes ~7, so I suspect there's something broken.

**Comment by slandelle** [comment]
CI stalled with tons of exceptions such as:
```
2016-11-29 10:07:00,856 [main] DEBUG org.asynchttpclient.AsyncCompletionHandler - com.sun.proxy.$Proxy14 cannot be cast to org.asynchttpclient.AsyncHandler
java.lang.ClassCastException: com.sun.proxy.$Proxy14 cannot be cast to org.asynchttpclient.AsyncHandler
	at org.asynchttpclient.filter.ReleasePermitOnComplete.wrap(ReleasePermitOnComplete.java:23)
	at org.asynchttpclient.filter.ThrottleRequestFilter.filter(ThrottleRequestFilter.java:62)
	at org.asynchttpclient.DefaultAsyncHttpClient.preProcessRequest(DefaultAsyncHttpClient.java:232)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:189)
	at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:39)
	at org.asynchttpclient.filter.FilterTest.basicTest(FilterTest.java:69)
```

**Comment by slandelle** [comment]
@markus-s24 Please ping once you're done

**Comment by markus-s24** [comment]
Sorry for the delay. It should be finally fixed now.

I have ignored the test, because they got stuck with no failure message. Maybe some timeout in the tests would be nice?

**Comment by slandelle** [comment]
> Maybe some timeout in the tests would be nice?

Well, if you can add that, it would be great! As I said, I don't use this part of the code, and I'm pretty swamped atm.

**Comment by slandelle** [comment]
Thanks!

**Pull request merged**
