### PR TITLE
Added a way to define a body in ReactiveStreamBodies

### PR DESCRIPTION
**Pull request by schmitch**
Actually this would be a approach for #1136

### CODE REVIEW

**Comment by slandelle** [comment]
@jroper Thought?

**Comment by jroper** [comment]
I think this makes sense, though it'd be good to see javadoc on `NettyBody` that describes how `getContentLength` is used - I'm assuming that if you return -1, that tells AHC to set the chunked headers and send a chunked body, otherwise it will set a content length.  Similar javadocs mentioning that -1 (or not setting at all) will lead to chunked encoding could also be added to `Request.getContentLength` and `RequestBuilderBase.setContentLength`, I guess.

**Comment by slandelle** [comment]
> I think this makes sense, though it'd be good to see javadoc on NettyBody that describes how getContentLength is used - I'm assuming that if you return -1, that tells AHC to set the chunked headers and send a chunked body, otherwise it will set a content length.

Agree, but on `Body` (the API), not `NettyBody` (impl). :)

> Similar javadocs mentioning that -1 (or not setting at all) will lead to chunked encoding could also be added to Request.getContentLength and RequestBuilderBase.setContentLength, I guess.

Actually, those were only used by the Grizzly and the JDK provider in 1.9. I missed that I should remove them in AHC2.

Thanks!

**Comment by slandelle** [comment]
Shoot, I didn't realize this PR was indeed introducing a request.getContentLength usage.
I'm going to revert the merge.

Let's then discuss how to bring a Content-Length there. It should be the Body's responsibility.

**Comment by schmitch** [comment]
Wouldn't my take won't be good enough? Or how do you mean "it should be the Body's responsibility". I mean it's a streamed response, but maybe the user already know the Content-Length and wants to set it btw. we could discuss in the issue I've created #1136 and I try my best to do it.

**Comment by slandelle** [comment]
> Wouldn't my take won't be good enough?

No. As of #1138, I just remove `Request.getContentLength`, and `RequestBuidler.setContentLength`. Those where dead code that were used by the Grizzly provider in AHC1.

> I mean it's a streamed response, but maybe the user already know the Content-Length and wants to set it btw.

Don't get me wrong, I agree with the feature (being able to set the Content-Length).
Not with the implementation (passed from the Request/RequestBuilder).

It would be confusing to have such methods in the Generic API that are only used from for ReactiveStreams.

**Comment by schmitch** [comment]
@slandelle see my edit, what about:
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestFactory.java#L169

Changing this part to check if there is a existing Header? i.e. either TRANSFER_ENCODING or CONTENT_LENGTH and keep it if it's there ?

**Comment by slandelle** [comment]
That looks like a very complicated way to me.

IMO, the proper solution would be to overload `RequestBuilderBase#setBody(Publisher<ByteBuffer>)` and introduce a version that takes a Content-Length and pass it to the `ReactiveStreamsBodyGenerator`.

**Comment by schmitch** [comment]
That would be fine to me too however that would mean we would need to change play-ws while the Header change wouldn't need a change. I open a new PR with your solution.

**Comment by slandelle** [comment]
> that would mean we would need to change play-ws while the Header change wouldn't need a change.

Well, from my pov, that's a new feature. :)

**Comment by schmitch** [comment]
https://github.com/AsyncHttpClient/async-http-client/pull/1139 opened, suggestions are welcomed so that I could fix it when I'm done with work. ;)

**Pull request merged**
