### PR TITLE
1632: Stop doing reverse DNS lookups

### PR DESCRIPTION
**Pull request by namiles**
See #1632

### CODE REVIEW

**Comment by namiles** [comment]
@slandelle My build failed due to `ChunkingTest.testBufferLargerThanFileWithStreamBodyGenerator()`. The test passes locally and I am relatively sure I didn't do anything that would affect this test. Is there a way to re-run a build?
```java
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost:37135 after 1000 ms
	at org.asynchttpclient.request.body.ChunkingTest.waitForAndAssertResponse(ChunkingTest.java:106)
	at org.asynchttpclient.request.body.ChunkingTest.doTestWithInputStreamBodyGenerator(ChunkingTest.java:61)
	at org.asynchttpclient.request.body.ChunkingTest.testBufferLargerThanFileWithStreamBodyGenerator(ChunkingTest.java:39)
Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost:37135 after 1000 ms
```

**Comment by namiles** [comment]
Looks like you lost [a build](https://travis-ci.org/AsyncHttpClient/async-http-client/builds/499114245) to the same test 3 months ago

**Comment by namiles** [comment]
I did
```
git commit --amend --no-edit
git push myfork issue-1632 -f
```
which re-ran the build and it passed this time

**Comment by slandelle** [comment]
Thanks!

**Pull request merged**
