### PR TITLE
Updating netty.version to latest to fix a vulnerability

### PR DESCRIPTION
**Pull request by ronanwatkins**
More detail: https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-1584063

### CODE REVIEW

**Comment by guizmaii** [comment]
@ronanwatkins The latest version is now `4.1.69.Final`, could you maybe update your PR, please?

Once this is done, @TomGranot would it be possible for you to publish a new version, please?

**Comment by borissmidt** [comment]
I also updated the netty version in this PR but added the new client codec options to the httpClientCodec client. in : #1804

**Review by rzwerus — APPROVED** [review]

**Comment by Dieken** [comment]
4.1.85.Final is released, when will this get merged?

**Comment by Dieken** [comment]
@hyperxpro why close? It’s not resolved, it’s a security issue.

**Comment by hyperxpro** [comment]
> @hyperxpro why close? It’s not resolved, it’s a security issue.

New major release will use latest Netty version. Checkout `develop` branch.

**Pull request closed without merging**
