### PR TITLE
Add  CompletableFuture usage example to Readme.md

### PR DESCRIPTION
**Pull request by fmcarvalho**
Include a simple use of AsyncHttpClient with CompletableFuture in README.md

### CODE REVIEW

**Comment by slandelle** [comment]
Hi,

Thanks for contributing.
However, I think it would be way better to contribute examples into a dedicated module inside this repository (that's [what Netty does](https://github.com/netty/netty/tree/4.1/example) for example) than to have a link pointing to your personal repo. Do you agree?

Cheers

**Comment by fmcarvalho** [comment]
Sorry for my late response. I agree and I will create that module. Following the naming conventions from [Netty example](https://github.com/netty/netty/tree/4.1/example) I am thinking to put this usage demo into a class `Continuations` in a package `org.asynchttpclient.example.continuations`. Is this ok? 

I am not sure about using the name `Continuations` or `Promise` or any other?

**Comment by slandelle** [comment]
Why not completable? It would be explicit that it's about CompletableFutures and not ReactiveStreams or something else.

**Comment by fmcarvalho** [comment]
Do you mean `asynchttpclient.example.completable.CompletableFutures`?

**Comment by slandelle** [comment]
yep

**Pull request closed without merging**
