### PR TITLE
Make WebSocketUpgradeHandler extensible in a controlled manner.

### PR DESCRIPTION
**Pull request by thabach**
Via protected template methods, make `WebSocketUpgradeHandler` extensible in a controlled manner.

### CODE REVIEW

**Comment by slandelle** [comment]
I probably won't be able to release before a few days.
Please ping if I forget.

**Comment by seamusmac** [comment]
@thabach @slandelle Thanks for this, will try to get wasync using this asap. No rush on release yet :)

**Comment by seamusmac** [comment]
There is one method setWebSocket, that I was overriding too, so I could grab an instance and use in the extension. Can we add that too?

**Comment by jfarcand** [comment]
@slandelle Merci :-)

**Comment by slandelle** [comment]
@seamusmac Go ahead.

@jfarcand De rien ;-)

**Comment by thabach** [comment]
@slandelle please merge #1447 - cheers !

**Comment by slandelle** [comment]
@thabach done

**Pull request merged**
