### PR TITLE
Update README with org.asynchttpclient

### PR DESCRIPTION
**Pull request by wsargent**
Unscarcifying documentation!

### CODE REVIEW

**Comment by slandelle** [comment]
> Unscarcifying documentation!

LOL.

Let's change the package names in the README when 2.0.0 is out and AHC1 is officially deprecated. I plan to do that along with Gatling 2.2.0 at the end of the month. I'll hold this PR on until then.

But then, I guess this isn't sufficient for most users. A second step would probably to migrate the sample from JFA's blog in here.

**Comment by wsargent** [comment]
> sample from JFA's blog 

What blog post sample?  I haven't heard of this.

**Comment by slandelle** [comment]
See links in one of the first lines in this README.

**Comment by wsargent** [comment]
I think the 2011 blog post isn't current for 1.9.x, even.

There's also https://asynchttpclient.github.io/async-http-client/ site which still has the 1.8.0-SNAPSHOT.

**Comment by wsargent** [comment]
woo!

**Pull request merged**
