### PR TITLE
Check in additional oauth tests

### PR DESCRIPTION
**Pull request by wsargent**
Adds a package level constructor for OAuthSignatureCalculator to directly set the nonce and timestamp for testing, and adds some tests to ensure that the requestbuilder is using the signature calculator correctly.

### CODE REVIEW

**Comment by slandelle** [comment]
I like the test, but I'm not found of adding 2 members just for tests. Why not simply delegate nonce and timestamp computation to protected methods that tests can override?

Note that you declared testTimestamp as a Long wrapper, but then handle it as a primitive, causing a possible NPE.

Thanks!

**Comment by slandelle** [comment]
@wsargent I'll merge and clean up as I suggested. Thanks!

**Comment by slandelle** [comment]
Ported on 1.9.x as of 692bad165714cb51f244eec6988781cd1f2204f1

**Comment by wsargent** [comment]
Thanks!

**Pull request merged**
