### PR TITLE
netty 4.1.107

### PR DESCRIPTION
**Pull request by sullis**
https://netty.io/news/2024/02/13/4-1-107-Final.html

io_uring
https://netty.io/news/2024/02/19/io_uring_0-0-25-Final.html

### CODE REVIEW

**Comment by sullis** [comment]
PTAL @hyperxpro

**Comment by sullis** [comment]
GitHub Actions build failure:

```
Error:    DefaultAsyncHttpClientTest.testNativeTransportWithoutEpollOnly:63 
Unexpected exception thrown: 
java.util.concurrent.ExecutionException: java.net.UnknownHostException: www.shieldblaze.com
```

**Review by hyperxpro — APPROVED** [review]

**Comment by sullis** [comment]
@hyperxpro  "UnknownHostException: www.shieldblaze.com"

**Comment by hyperxpro** [comment]
lol weird, lemme point DNS to somewhere else.

**Comment by sullis** [comment]
Ready to merge

**Pull request merged**
