### PR TITLE
#1238 replace AHC Base64 with java.util.Base64

### PR DESCRIPTION
**Pull request by doom369**
Fixes https://github.com/AsyncHttpClient/async-http-client/issues/1238

### CODE REVIEW

**Comment by slandelle** [comment]
No way I'll ever merge that without benchmarks, my friend!
Also, there are different flavors of Base64 and I'm not even sure of which should be used where...

**Comment by doom369** [comment]
@slandelle hah, let me prepare benchmark.

> Also, there are different flavors of Base64 and I'm not even sure of which should be used where...

Comment in removed Base64 says it RFC 2045. However, that is not true, as RFC 2045 uses \r\n. So used default that is RFC4648.

**Comment by doom369** [comment]
@slandelle here you go:

```
Benchmark                          Mode  Cnt    Score    Error  Units
Base64PerfTest.AHC_BASE64_decode   avgt   20  102.123 ±  2.570  ns/op
Base64PerfTest.AHC_BASE64_encode   avgt   20  205.752 ± 11.434  ns/op
Base64PerfTest.JAVA_BASE64_decode  avgt   20  123.675 ± 18.390  ns/op
Base64PerfTest.JAVA_BASE64_encode  avgt   20   74.210 ±  3.350  ns/op
```

Benchmark:

```
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(1)
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 20, time = 1)
public class Base64PerfTest {

    private String d = "TlRMTVNTUAACAAAAAAAAACgAAAABggAAU3J2Tm9uY2UAAAAAAAAAAA==";
    private byte[] e = Base64.getDecoder().decode(d);

    @Benchmark
    public byte[] AHC_BASE64_decode() {
        return Base64AHC.decode(d);
    }

    @Benchmark
    public byte[] JAVA_BASE64_decode() {
        return Base64.getDecoder().decode(d);
    }

    @Benchmark
    public String AHC_BASE64_encode() {
        return Base64AHC.encode(e);
    }

    @Benchmark
    public String JAVA_BASE64_encode() {
        return Base64.getEncoder().encodeToString(e);
    }
}
```

**Comment by slandelle** [comment]
> Comment in removed Base64 says it RFC 2045. However, that is not true, as RFC 2045 uses \r\n.

Yeah, I suspected that Base64 AHC usage was a mess... :(
Usage should be revised on every use case: NTML, OAuth, Basic and WebSocket keys.

> JDK 9.0.1, VM 9.0.1+11
> I think this is very good result so AHC can move to JDK Base64.

I'll run this benchmark on JDK 8 too.

**Comment by doom369** [comment]
> I'll run this benchmark on JDK 8 too.

Sure. Waiting for your results.

**Comment by slandelle** [comment]
Benchmarks on my machine:

Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

```
Benchmark                          Mode  Cnt    Score   Error  Units
Base64PerfTest.AHC_BASE64_decode   avgt   20   88,274 ± 1,054  ns/op
Base64PerfTest.AHC_BASE64_encode   avgt   20  188,539 ± 3,086  ns/op
Base64PerfTest.JAVA_BASE64_decode  avgt   20  182,451 ± 2,861  ns/op
Base64PerfTest.JAVA_BASE64_encode  avgt   20  114,778 ± 1,689  ns/op
```

Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

```
Benchmark                          Mode  Cnt    Score    Error  Units
Base64PerfTest.AHC_BASE64_decode   avgt   20   82,235 ±  1,504  ns/op
Base64PerfTest.AHC_BASE64_encode   avgt   20  231,056 ± 24,291  ns/op
Base64PerfTest.JAVA_BASE64_decode  avgt   20  125,373 ±  2,797  ns/op
Base64PerfTest.JAVA_BASE64_encode  avgt   20   71,306 ±  0,650  ns/op
```

**Comment by slandelle** [comment]
So it seems Java 9 got better Base64 encoding.

**Comment by slandelle** [comment]
Anyway, let's do this, as I'm more confident in Java's implementation atm.

**Comment by slandelle** [comment]
thanks!

**Comment by doom369** [comment]
Yeah. That is good move, especially with new Java release circle and future performance improvements.

**Comment by slandelle** [comment]
> Yeah. That is good move, especially with new Java release circle and future performance improvements.

Java 9 improved things and broke others, eg most parsers are doing worse because of the new String implementation.

**Pull request merged**
