### PR TITLE
support zstd compression

### PR DESCRIPTION
**Pull request by sullis**
### Context

Netty supports zstd compression.

https://github.com/luben/zstd-jni

### CODE REVIEW

**Comment by sullis** [comment]
WDYT @hyperxpro

**Comment by hyperxpro** [comment]
Can you add license?

**Comment by sullis** [comment]
> Can you add license?

Done.

**Comment by hyperxpro** [comment]
We require more end-to-end tests.

**Comment by sullis** [comment]
PTAL @hyperxpro

**Comment by sullis** [comment]
> We require more end-to-end tests.

I added a couple of new tests in this file:  
```
AutomaticDecompressionTest.java
```

**Comment by sullis** [comment]
Ready for review.

**Comment by sullis** [comment]
Rebased.

**Comment by sullis** [comment]
Ready for review @hyperxpro

**Review by hyperxpro — APPROVED** [review]

**Comment by hyperxpro** [comment]
Sorry, I was on vacation for the past 2 weeks.

LGTM!

**Comment by hyperxpro** [comment]
Thanks a lot!

**Pull request merged**
