### PR TITLE
Upgrade Netty 4.1.42 -> 4.1.44

### PR DESCRIPTION
**Pull request by aheritier**
It is including 2 security fixes:

* https://snyk.io/vuln/SNYK-JAVA-IONETTY-543669
* https://snyk.io/vuln/SNYK-JAVA-IONETTY-543490

### CODE REVIEW

**Comment by slandelle** [comment]
Thanks, but well, those are server side issues... :)

**Comment by aheritier** [comment]
LOL good catch. Thanks @slandelle (stupid security checks which are blaming all deps. Ref: https://github.com/cloudbees/zendesk-java-client/issues/330

**Comment by slandelle** [comment]
Moreover, there's are 2 pretty nasty regressions in Netty 4.1.44, so it shouldn't be use and users should upgrade to 4.1.15 instead.

**Comment by aheritier** [comment]
🤦‍♂ #sorry

**Comment by aheritier** [comment]
You can rollback my PR if it's too dangerous to upgrade @slandelle

**Comment by slandelle** [comment]
No pro, I've updated to 4.1.45 after you.

**Comment by qunayu** [comment]
Hey, do we know when this change will be rolled out?

**Pull request merged**
