### PR TITLE
Fix NPE in ThreadSafeHMAC when secret is not set

### PR DESCRIPTION
**Pull request by bomgar**
apparently the '&' is important even if no secret is present

### CODE REVIEW

**Comment by slandelle** [comment]
Sorry, but what does this fix exactly? Could you provide a test case that fails without it?

**Comment by bomgar** [comment]
Test added.
The OAuthSignatureCalculator already handles it correctly if the user key is null. But the secret causes a NPE in the ThreadSafeHMAC.

**Comment by slandelle** [comment]
Isn't the secret mandatory?

**Comment by bomgar** [comment]
The user key and secret are not necessary. It is possible to authenticate a consumer only.

**Comment by slandelle** [comment]
Thanks!

**Pull request merged**
