### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by vietj**

### CODE REVIEW

**Comment by slandelle** [comment]
Ah ah, thanks, man!
Having a look at what other HTTP clients do?

**Comment by vietj** [comment]
LOL yes :-)

**Comment by vietj** [comment]
it's been asked for long time in vert.x but never really had time to do it

**Comment by slandelle** [comment]
Yours' on my plate too ;-)

**Comment by vietj** [comment]
btw you need to come at MarsJUG sometimes, so we can have a beer and talk about many things!

**Comment by slandelle** [comment]
Would love to :) I'd have to come up with a topic for a talk. Mostly focused on our FrontLine product atm, hence not OSS.
Then, I guess we'll be able to meet at DevoxxFR :)

**Comment by vietj** [comment]
yes, crossing fingers for being at DevoxxFR though. I'm glad you took me to Gil Tene's session 3 years ago!

**Comment by slandelle** [comment]
Oh my. First, time sure flies by. Then: I'm getting damn old :( :( :(

**Pull request merged**
