### PR TITLE
netty 4.1.110

### PR DESCRIPTION
**Pull request by sullis**
https://netty.io/news/2024/05/22/4-1-110-Final.html

### CODE REVIEW

**Comment by sullis** [comment]
image

**Comment by sullis** [comment]
GitHub Actions build is failing due to this error:

```
Execution java.net.UnknownHostException: www.shieldblaze.com
```

cc: @hyperxpro

**Comment by sullis** [comment]
lgtm

**Review by hyperxpro — APPROVED** [review]
:)

**Pull request merged**
